# Generated by Django 3.0 on 2020-11-28 18:00

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.StudentProfile.upload_location),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='education1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='education2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='education3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='upload_images/default.png', null=True, upload_to=account.models.TeacherProfile.upload_location),
        ),
    ]
