# Generated by Django 3.0 on 2020-12-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201128_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
