# Generated by Django 3.0 on 2020-12-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201128_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefile',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
